{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pymongo import MongoClient\n",
    "import glob\n",
    "import json"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "# client = MongoClient('mongodb+srv://user:user@cluster0.ard5c.mongodb.net/test')\n",
    "client = MongoClient('mongodb://localhost:27017/')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "db = client.get_database('tweets')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "nlp-dev\n"
     ]
    }
   ],
   "source": [
    "#### API Client\n",
    "\n",
    "import os\n",
    "print (os.environ['CONDA_DEFAULT_ENV'])\n",
    "\n",
    "import tweepy\n",
    "import webbrowser\n",
    "import time\n",
    "import pandas as pd\n",
    "import csv\n",
    "import json\n",
    "import requests\n",
    "\n",
    "# Akila\n",
    "\n",
    "consumer_key = \"glPtgXbmiZBf7U4IzqdKefwnJ\"\n",
    "consumer_secret = \"O2Iu1L0MAQi4NxhGZwq7AX4JnMrFdt6uT0MHxAJsxBhCiPqLFZ\"\n",
    "\n",
    "access_token = \"1209349665935654913-VNbgDoNbb5CXgvs5zFhZ2wXHIW37xG\"\n",
    "token_secret = \"sf9grQsT0y1g82zxk9HlfL7ALALIA3rkYg3WjDy2yEUui\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Authenticate to Twitter\n",
    "try:\n",
    "    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)\n",
    "    auth.set_access_token(access_token, token_secret) \n",
    "except tweepy.TweepError as e:\n",
    "    print(e)\n",
    "    \n",
    "\n",
    "# Create API object\n",
    "api = tweepy.API(auth, wait_on_rate_limit=True,\n",
    "    wait_on_rate_limit_notify=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# # Group tweets by root tweet id (grater tha 200 retweets)\n",
    "# for rating_type in ['false']:\n",
    "#     for i in range(2,3):\n",
    "#         flag = True\n",
    "#         while flag:\n",
    "#             try:\n",
    "#                 cascade_root_user_ids = set()\n",
    "#                 # collection name\n",
    "#                 COLLECTION_NAME = 'data_{}_{}'.format(rating_type, i)\n",
    "#                 print(COLLECTION_NAME, 'trying to collect...')\n",
    "                \n",
    "#                 # populate existing user_ids\n",
    "#                 records = db['followers']\n",
    "#                 populated_documents = records.find()\n",
    "#                 populated_user_ids = []\n",
    "#                 for document in populated_documents:\n",
    "#                     populated_user_ids.append(document['user_id'])\n",
    "#                 print('Initalizing population...')\n",
    "                \n",
    "#                 records = db[COLLECTION_NAME]\n",
    "#                 cursor = records.find({'retweeted_status.retweet_count' : { '$gt' :200 } }, batch_size = 10)\n",
    "#                 for record in cursor:\n",
    "#                     user_id = record['user']['id']\n",
    "#                     if user_id not in populated_user_ids:\n",
    "#                         try:\n",
    "#                             cascade_root_user_ids.add(record['retweeted_status']['id'])\n",
    "#                             records = db['followers']               \n",
    "#                             records.insert_one({'user_id' : user_id, 'followers' : []})\n",
    "#                             try:\n",
    "#                                 print('collecting...', user_id)\n",
    "#                                 for follower in tweepy.Cursor(api.followers_ids, user_id = user_id).items(10000000):\n",
    "#                                     records.update_one({'user_id' : user_id}, {'$push' : {'followers' : follower}})\n",
    "#                             except tweepy.TweepError as e:\n",
    "#                                 if 'Failed to send request:' in e.reason:\n",
    "#                                     print('Time out error caught.', e)\n",
    "#                                     time.sleep(180)\n",
    "#                                     continue\n",
    "#                         except (AttributeError, KeyError) as e:\n",
    "#                             print('AttributeError, KeyError failed')\n",
    "#                             continue\n",
    "#                 cursor = records.find({'retweeted_status.retweet_count' : { '$gt' :200 } }, batch_size = 10)\n",
    "#                 user_ids = list(record['user']['id'] for record in cursor )\n",
    "#                 print(type(user_ids), len(user_ids))\n",
    "#                 print(type(populated_user_ids), len(populated_user_ids))\n",
    "#                 if set(user_ids).issubset(set(populated_user_ids)):\n",
    "#                     flag = False\n",
    "#             except Exception as e:\n",
    "#                 print(e, ' OR Connection failed')\n",
    "#                 time.sleep(180)\n",
    "#                 continue"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "scrolled": true,
    "tags": []
   },
   "outputs": [],
   "source": [
    "# em =[]\n",
    "# for cursor in db['followers'].find({'user_id': {'$in': ROOT_USERS},'followers' : {'$exists': True , '$not': {'$size': 0} } }):\n",
    "#     em.append(cursor['user_id'])\n",
    "#     print(cursor['user_id'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ROOT_USERS = [1537219201]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "# pip install tweepy --u"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "# tweepy.__version__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "scrolled": true,
    "tags": []
   },
   "outputs": [],
   "source": [
    "# api.followers_ids(ROOT_USERS[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "# api.user_timeline(ROOT_USERS[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "# len(em)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "ROOT_USERS = [3836684302, 42070045, 17201184, 2489085984, 45989925, 2922512422, 1250646188107448320, 840194109017075714, 1089312665288077313, 161364032, 886875065937141761, 1369384738830618634, 1154060799683567617, 1168363259709161472, 1313868235599740929, 60805234, 1088301280240357376, 893850481776353280, 14268564, 430694565, 1364006103063748608, 20820150, 2370150583, 3590783172, 27404490, 299270358, 166869214, 2547108063, 2421737695, 827691235, 375757041, 229677300, 371949816, 21344507, 1080173963072937984, 1316722900016263169, 1149544355062882305, 948216080, 4924987672, 35254557, 868940253201125377, 1373959121440014344, 1258514841637203968, 17387823, 68667695, 1367458872420687872, 984732077332582400, 1179451184978939905, 2987516222, 17600832, 577352005, 1085055308, 235841871, 838302038, 158816604, 863161360129159168, 2494450028, 492833134, 789586492956020736, 1191207303082586112, 15391102, 1250919644229259267, 15446424, 305580442, 315543965, 825074418011471874, 406274470, 1350843303864881153, 233134506, 26982826, 1067213298708303872, 875178422, 410325434, 848423354, 15567292, 922152574777790465, 1385249273017688074, 1066399723714695168, 15694286, 2258332112, 259985878, 56517100, 2953511406, 1297213690467487744, 1353165646750748672, 1009862956199206913, 3154147845, 4784927239, 369711636, 3609635354, 1486449198, 17103426, 1161749626065756161, 305902153, 904283597988782082, 16538186, 221559373, 434305617, 364884563, 1381888596, 1028875887029055488, 80769628, 1143985977536290816, 4086608482, 1364996629871267840, 909754855144738816, 1230667117852151809, 940022228623618048, 1024117285106196480, 1657471614, 844149235205386241, 42410634, 1181716915590438912, 43750028, 910524584973045760, 4173347475, 38845076, 370524828, 1257464504025092097, 76505761, 56470183, 1350100588219011073, 1279872606917857280, 989966588781694976, 15917758, 1155670722, 1007664341695361024, 1060238593640275969, 1241244607545032704, 1244815842388447232, 1026461628336926720, 219179731, 1372996920403234826, 1322991169828196352, 755555053, 415132414, 1211465545503014913, 821961366986702848, 248869641, 1389590876356325379, 752432706768629760, 31537951, 66075435, 378778417, 805892916, 125113143, 1256264171022438406, 826619023785746432, 590619454, 1366848690934206464, 518615888, 1042954573747351552, 3023606622, 2182990690, 1199832940387209216, 282841967, 1243839828887732224, 2155117434, 2773848960, 16356226, 832680836, 1296062276055769089, 1353069759852474371, 39744402, 408275864, 1243848705616351233, 3009921950, 1086644975612366849, 1312387913393545217, 131466176, 2312494016, 1328423212041052164, 12413892, 15823826, 2880447465, 910221858674319360, 1365899057307152385, 974138693547016192, 1231833435544719360, 36692984, 1134948881014448129, 130956302, 511108114, 20751391, 1091870089350127617, 3186934824, 37352500, 1279363283171119105, 15791186, 1264563889225768962, 1307184212, 1179879521228480512, 372614252, 269843571, 2555864189, 3350742148, 150549638, 26684553, 26270864, 790019230389248000, 1309538480528162819, 2884771, 1338002648012713984, 872494254, 1347005469345402881, 483347643, 1381363018060161034, 231494844, 25728193, 58006725, 44868806, 1363295931161075713, 766786784, 1403032802, 38616293, 988503217947512837, 15308015, 19870967, 259716345, 227179769, 269868286, 232189184, 2582951192, 351896858, 877932062208139264, 1248212393873850368, 429788453, 48848172, 233581875, 746412932360208384, 40265017, 357506382, 1213635078120558592, 1365266542297042948, 1090287502475317248, 1161778542, 783431408215666688, 2321122672, 778653042, 336840057, 14859642, 4281568632, 36638077, 55065988, 1400937864, 2358699408, 1120053573214191616, 270159255, 1275445355828482053, 45399457, 15304100, 265467303, 2579152296, 221980075, 1349745998126571523, 20583865, 162446785, 930044881447383045, 263822801, 2305422800, 1202948085627969537, 595156433, 795719786177167360, 4876670430, 958086874194735106, 14296548, 1359927567298494479, 1288248240366694400, 1088664900270837761, 4801844714, 165535216, 2683923952, 154140150, 177804792, 1152287077809238018, 1247566352447045637, 1082331771398746112, 175724046, 278124059, 1102281363179356160, 1385330844793851906, 2853621284, 80862758, 738567336853020673, 2928647725, 12721712, 1353379058562736135, 1265791990031138817, 59104830, 24647233, 1222356916216696833, 1605912138, 4835333710, 441208401, 1975658071, 60116572, 1083915256374673409, 758473026367266816, 1359092237259452426, 62643826, 1903472244, 15232635, 155815554, 4531838592, 217333380, 34053771, 1185866471219617792, 3492855441, 969860836163547136, 28337813, 1235815107579404290, 2727587493, 24563371, 401788588, 406040240, 75304637, 2166101695, 22208192, 1063354658910015488, 1043312766776356864, 227325663, 376794851, 14061303, 1090072850403393536, 1268286099547398144, 150062849, 21786370, 734820676448686080, 809873343524569089, 591312648, 811768906301968384, 1128939284, 1160836885, 1250608920, 1277623223270535171, 921381466260480001, 1321089119968178183, 499498789, 48856880, 1245944142632386565, 1382974089455800320, 296513340, 64354119, 105488203, 14511951, 119656272, 1199852689552592896, 1319677459768496132, 871367023237906432, 154961762, 3243356006, 1044060734806790144, 596772719, 953632523053084672, 1166893803275317248, 1132426313959190531, 17862527, 1136015233, 258617217, 15533969, 1141772224992620545, 335015833, 27000730, 1339869053637320706, 1276164000, 1130196896, 57247652, 2784010149, 951908614494720000, 548562871, 76771256, 84109239, 907646706895937536, 79243199, 1213460475918180352, 952590357467824128, 59047876, 824651197160108032, 2975932363, 10921932, 700241870, 2294443982, 929021269256925184, 293421019, 3025790949, 1316911412531351553, 4917121001, 712857339406245888, 2317735927, 22994942]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "collecting... 299270358\n",
      "collecting... 2547108063\n",
      "collecting... 2421737695\n",
      "collecting... 827691235\n",
      "collecting... 375757041\n",
      "collecting... 229677300\n",
      "collecting... 371949816\n",
      "collecting... 21344507\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=1582004359782501589&user_id=21344507 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0C15A770>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1080173963072937984\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1080173963072937984 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0C15A570>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1316722900016263169\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1316722900016263169 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1149544355062882305\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1149544355062882305 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08478810>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 948216080\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=948216080 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x088122D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 4924987672\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=4924987672 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0C15AE50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 35254557\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=35254557 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B270>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 868940253201125377\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=868940253201125377 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11BD90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1373959121440014344\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1373959121440014344 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B930>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1258514841637203968\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1258514841637203968 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11BB70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 17387823\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=17387823 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11BE10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 68667695\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=68667695 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05F6C730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1367458872420687872\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1367458872420687872 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492D10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 984732077332582400\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=984732077332582400 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492630>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1179451184978939905\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1179451184978939905 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0834CE30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 2987516222\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=2987516222 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 577352005\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=577352005 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B6B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1085055308\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1085055308 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 235841871\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=235841871 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 838302038\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=838302038 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 158816604\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=158816604 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B150>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 863161360129159168\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=863161360129159168 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0C15A450>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 2494450028\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=2494450028 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 492833134\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=492833134 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084927B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 789586492956020736\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=789586492956020736 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492CF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1191207303082586112\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1191207303082586112 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492E90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 15391102\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=15391102 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492450>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1250919644229259267\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1250919644229259267 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x07FB1770>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 15446424\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=15446424 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B8F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 305580442\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=305580442 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11BC90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 315543965\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=315543965 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05D14590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 406274470\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=406274470 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05D14590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1350843303864881153\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1350843303864881153 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B8D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 233134506\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=233134506 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11BAB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 26982826\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=26982826 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1067213298708303872\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1067213298708303872 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492B10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 875178422\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=875178422 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 410325434\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=410325434 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11BCB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 848423354\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=848423354 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B0B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 15567292\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=15567292 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0835DE30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 922152574777790465\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=922152574777790465 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x06535E10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1385249273017688074\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1385249273017688074 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05F6C710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1066399723714695168\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1066399723714695168 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B5D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 15694286\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=15694286 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0C15AC30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 2258332112\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=2258332112 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0C15AE50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 259985878\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=259985878 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492BD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 56517100\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=56517100 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492B10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 2953511406\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=2953511406 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08812350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1297213690467487744\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1297213690467487744 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08812470>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1009862956199206913\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1009862956199206913 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0C15A2D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 3154147845\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=3154147845 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05F6C290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 4784927239\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=4784927239 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0835DFB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 369711636\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=369711636 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B1B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 3609635354\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=3609635354 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05D14590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1486449198\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1486449198 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B270>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 17103426\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=17103426 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x07FB1770>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1161749626065756161\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1161749626065756161 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0C15A030>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 305902153\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=305902153 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 904283597988782082\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=904283597988782082 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05F6C730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 16538186\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=16538186 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08812090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 221559373\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=221559373 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 434305617\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=434305617 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11BA50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 364884563\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=364884563 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05F6C530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1381888596\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1381888596 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1028875887029055488\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1028875887029055488 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0C15A770>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 80769628\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=80769628 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0C15A2D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1143985977536290816\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1143985977536290816 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492B10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 4086608482\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=4086608482 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1364996629871267840\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1364996629871267840 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x07BC63F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 909754855144738816\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=909754855144738816 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0835DE30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1230667117852151809\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1230667117852151809 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08812030>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 940022228623618048\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=940022228623618048 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1024117285106196480\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1024117285106196480 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B270>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 844149235205386241\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=844149235205386241 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11BE30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 42410634\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=42410634 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B2B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1181716915590438912\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1181716915590438912 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05F6C530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 43750028\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=43750028 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08395AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 910524584973045760\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=910524584973045760 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08395AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 4173347475\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=4173347475 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x06535D30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 38845076\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=38845076 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084929D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 370524828\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=370524828 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0834CE10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 76505761\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=76505761 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492CB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 56470183\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=56470183 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B270>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1350100588219011073\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1350100588219011073 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B770>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1279872606917857280\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1279872606917857280 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B4F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 989966588781694976\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=989966588781694976 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11BE50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 15917758\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=15917758 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11BE30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1155670722\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1155670722 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B930>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1007664341695361024\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1007664341695361024 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05D14410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1060238593640275969\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1060238593640275969 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x07796AB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1241244607545032704\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1241244607545032704 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05D14590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 219179731\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=219179731 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084928B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1372996920403234826\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1372996920403234826 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0834CDB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1322991169828196352\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1322991169828196352 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11BE90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 755555053\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=755555053 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11BEB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 415132414\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=415132414 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x07796AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1211465545503014913\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1211465545503014913 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B8F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 821961366986702848\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=821961366986702848 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 248869641\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=248869641 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11BAF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 1389590876356325379\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=1389590876356325379 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A11B5B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 752432706768629760\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=752432706768629760 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05F6C270>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 31537951\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=31537951 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492E90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 66075435\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=66075435 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 378778417\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=378778417 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x08492230>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 805892916\n",
      "Time out error caught. Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/ids.json?cursor=-1&user_id=805892916 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05F6C530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "collecting... 125113143\n",
      "collecting... 1256264171022438406\n",
      "collecting... 826619023785746432\n",
      "collecting... 590619454\n",
      "collecting... 1366848690934206464\n",
      "collecting... 518615888\n"
     ]
    }
   ],
   "source": [
    "# populate existing user_ids\n",
    "records = db['followers']\n",
    "populated_documents = records.find()\n",
    "populated_user_ids = []\n",
    "for document in populated_documents:\n",
    "    populated_user_ids.append(document['user_id'])\n",
    "for user_id in ROOT_USERS:\n",
    "    if user_id not in populated_user_ids:\n",
    "        try:\n",
    "            records = db['followers']               \n",
    "            records.insert_one({'user_id' : user_id, 'followers' : []})\n",
    "            try:\n",
    "                print('collecting...', user_id)\n",
    "                for follower in tweepy.Cursor(api.followers_ids, user_id = user_id).items(10000000):\n",
    "                    records.update_one({'user_id' : user_id}, {'$push' : {'followers' : follower}})\n",
    "#                     print(follower)\n",
    "            except tweepy.TweepError as e:\n",
    "                if 'Failed to send request:' in e.reason:\n",
    "                    print('Time out error caught.', e)\n",
    "                    time.sleep(180)\n",
    "                    continue\n",
    "        except Exception as e:\n",
    "            print(e, ' OR Connection failed')\n",
    "            time.sleep(180)\n",
    "            continue"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# for user_id in ROOT_USERS:\n",
    "#     print(user_id)\n",
    "#     records = db['followers']\n",
    "#     records.insert_one({'user_id' : user_id, 'followers' : []})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# for cursor in db['followers'].find({'user_id': ROOT_USERS[0]}):\n",
    "#     print(cursor['followers'])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
